name: "Synopsys Intelligent Security Scan"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  analyze:
    name: Analyze
    runs-on: [self-hosted, macOS, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Intelligent Orchestration
      run: |
            if [ ! -d 'io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}' ]; then
              wget "${{secrets.IO_CLIENT_URL}}/download/io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}.zip"
              unzip -o io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}.zip
              chmod a+x ./runBlackDuckScan.sh
            fi
            chmod +x io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}/io
            io_client-${{secrets.IO_CLIENT_VERSION}}-${{secrets.RUNNER_OS_TYPE}}/io --stage io --stage execution --stage workflow --adapters adapters.json
            if test -f "wf-output.json"; then
              cat wf-output.json
            fi
      env:
        # IO
        SYNOPSYS_IO_Workflow_Engine_Version : 2022.7.0
        SYNOPSYS_IO_io_server_token: ${{secrets.IO_SERVER_TOKEN}}
        SYNOPSYS_IO_io_server_url: ${{secrets.IO_SERVER_URL}}
        SYNOPSYS_IO_project_name: 'Jonny'
        SYNOPSYS_IO_persona_type: devsecops                               # Options: devsecops or developer
        SYNOPSYS_IO_project_release_type: "major"                         # Options: major or minor (only used when persona is developer)

        # SCM
        SYNOPSYS_IO_scm_type: "github"
        SYNOPSYS_IO_scm_owner: 'desantis731'
        SYNOPSYS_IO_scm_repository_name: 'https://github.com/desantis731/synopsys_github_action'
        SYNOPSYS_IO_scm_repository_branch_name: 'main'
        # SCM - GitHub
        SYNOPSYS_IO_github_token: ${{secrets.GITHUB_ACCESS_TOKEN}}
        SYNOPSYS_IO_github_username: ${{secrets.GITHUB_USERNAME}}
        SYNOPSYS_IO_github_apiUrl: "https://api.github.com/repos"

        # BTS - JIRA
        #SYNOPSYS_IO_Jira_hostUrl: ${{secrets.JIRA_URL}}
        #SYNOPSYS_IO_Jira_authToken: ${{secrets.JIRA_AUTH_TOKEN}}
        #SYNOPSYS_IO_Jira_username: "Administrator"
        #SYNOPSYS_IO_Jira_issueType: "Bug"
        #SYNOPSYS_IO_Jira_project_key: '<jira-project-key>'
        #SYNOPSYS_IO_jira_project_name: '<jira-project-name>'
        #SYNOPSYS_IO_Jira_assignee: "Administrator"
        #SYNOPSYS_IO_jira_issuesQuery: "resolution=Unresolved"

        # ASOC -  Code Dx
        #SYNOPSYS_IO_codedx_instanceUrl: ${{secrets.CODEDX_URL}}
        #SYNOPSYS_IO_codedx_apiKey: ${{secrets.CODEDX_ACCESS_TOKEN}}
        #SYNOPSYS_IO_codedx_projectId: '<codedx-project-id>'

        # Notifications - Slack
        #SYNOPSYS_IO_slack_channelIdentifier: '<slack-channel-identifier>'
        #SYNOPSYS_IO_slack_bearerToken: ${{secrets.SLACK_TOKEN}}

        # AST - Sigma
        #SYNOPSYS_IO_sigma_downloadurl: '<sigma-download-url>'

        # AST - Coverity
        #SYNOPSYS_IO_coverity_filepath: '<coverity-results-file-path>'
        #SYNOPSYS_IO_coverity_instanceurl: ${{secrets.COVERITY_URL}}
        #SYNOPSYS_IO_coverity_password: ${{secrets.COVERITY_PASSWORD}}
        #SYNOPSYS_IO_coverity_username: ${{secrets.COVERITY_USERNAME}}
        #SYNOPSYS_IO_coverity_stream: '<coverity-project-stream>'

        # AST - Polaris
        #SYNOPSYS_IO_polaris_instanceurl: ${{secrets.POLARIS_SERVER_URL}}
        #SYNOPSYS_IO_polaris_authtoken:  ${{secrets.POLARIS_ACCESS_TOKEN}}
        #SYNOPSYS_IO_polaris_projectName: '<polaris-project-name>'

        # AST - Black Duck
        SYNOPSYS_IO_Blackduck_AuthToken: ${{secrets.BLACKDUCK_TOKEN}}
        SYNOPSYS_IO_Blackduck_ProjectName: 'Jonny'
        SYNOPSYS_IO_Blackduck_InstanceUrl: ${{secrets.BLACKDUCK_URL}}
        SYNOPSYS_IO_Blackduck_ProjectVersion: 'IO_2'
