name: Black Duck SCA GitHub Action

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted, macOS, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Black Duck Full Scan
        if: ${{ github.event_name == 'push' }}
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        env: 
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_EXCLUDED_DETECTOR_TYPES: 'GIT'
          #DETECT_TOOLS_EXCLUDED: SIGNATURE_SCAN
          #DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: BLOCKER,CRITICAL,MAJOR,MINOR
          #DETECT_PROJECT_USER_GROUPS: plat-portal-admins,plat-portal-users
          #DETECT_WAIT_FOR_RESULTS: TRUE
          #DETECT_PROJECT_CODELOCATION_UNMAP: true
          DETECT_ACCURACY_REQUIRED: NONE
          DETECT_TIMEOUT: 3600
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          BLACKDUCK_TRUST_CERT: true
          DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
          #DETECT_EXCLUDED_DIRECTORIES:
        with:
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_scan_full: true
          github_token: ${{ secrets.GH_TOKEN }}
          #blackducksca_waitForScan: false
          #include_diagnostics: true
          blackducksca_scan_failure_severities: "ALL"
          
          #Optional- To enable feedback from Black Duck security testing as pull request comment
          #blackduck_automation_prcomment: true
          #Optional- To enable autoamtic fix pull request creation if vulnerabilities are reported
          #blackduck_automation_fixpr: true
          #Mandatory if blackduck_automation_fixpr or blackduck_automation_prcomment is set true
          #github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Black Duck PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        ### Use below configurations to set specific detect environment varibales
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          #DETECT_PROJECT_VERSION_NAME: main
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_EXCLUDED_DETECTOR_TYPES: 'GIT'
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          BLACKDUCK_TRUST_CERT: true
          DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
          DETECT_ACCURACY_REQUIRED: NONE
        with:
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_scan_full: false
          ### Accepts Multiple Values
          blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          ### Below configuration is used to enable automatic pull request comment based on Black Duck scan result
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_automation_prcomment is set to 'true'
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
