name: Synopsys Security Testing

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Black Duck PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.8.0
        ### Use below configurations to set specific detect environment varibales
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: main
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_EXCLUDED_DETECTOR_TYPES: 'GIT'
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          BLACKDUCK_TRUST_CERT: true
          DETECT_BLACKDUCK_RAPID_COMPARE_MODE: ALL
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_scan_full: false
          ### Accepts Multiple Values
          #blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          ### Below configuration is used to enable automatic pull request comment based on Black Duck scan result
          blackduck_automation_prcomment: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_automation_prcomment is set to 'true'
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
